name: nodejs-feature-branch-workflow

on:
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string

      component:
        description: 'Component name'
        required: true
        type: string

jobs:
  trigger:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Show project information
        run: |
          echo "Project: ${{ inputs.project }}"
          echo "Component: ${{ inputs.component }}"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Runner: $(hostname)"
          echo "User: $(whoami)"