apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-actions-demo
  template:
    metadata:
      labels:
        app: github-actions-demo
    spec:
      containers:
        - name: github-actions-demo
          image: tessydocker/github-actions-demo:v1
          ports:
            - containerPort: 80