name: Docker Test

on:
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-actions-demo:v1 .

      - name: Run container
        run: |
          docker run -d \
            --name github-actions-demo \
            -p 8080:80 \
            github-actions-demo:v1

      - name: Test application
        run: |
          sleep 5
          curl -f http://localhost:8080

      - name: Show container status
        run: docker ps

      - name: Stop container
        if: always()
        run: docker rm -f github-actions-demo