name: Docker Push

on:
  workflow_dispatch:

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-actions-demo:v1 .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy scan
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            github-actions-demo:v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image
        run: |
          docker tag github-actions-demo:v1 \
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:v1

      - name: Push image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:v1