name: AWS OIDC Debug

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug OIDC claims
        uses: github/actions-oidc-debugger@main