name: CI Practice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Check Linux
        run: |
          echo "Running on GitHub Actions"
          uname -a
          whoami
          pwd