name: Feature Pipeline

on:
  workflow_dispatch:

jobs:
  feature-pipeline:
    uses: yericharla123/workflows/.github/workflows/nodejs-feature-pipeline.yml@main

    with:
      project: roboshop
      component: catalogue

