name: NodeJS Feature Pipeline

on:
  workflow_call:
    inputs:
      project:
        description: "Project name"
        required: true
        type: string

      component:
        description: "Component name"
        required: true
        type: string

jobs:
  feature-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show pipeline information
        run: |
          echo "=============================="
          echo "Project   : ${{ inputs.project }}"
          echo "Component : ${{ inputs.component }}"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch    : $GITHUB_REF_NAME"
          echo "Hostname  : $(hostname)"
          echo "User      : $(whoami)"
          echo "=============================="
